#Requires -Version 5.1
<#
Sets up (or resets) the instructor's own live-demo repo: the exact same
Trailhead Cafe environment every team gets, generated by the already-tested
speedrun/setup-team.ps1 under the hood. This is YOUR repo to drive at the
front of the room while walking through demo-script.md and the visualizer --
separate from any team's folder, safe to reset between classes/runs.

Usage:
  .\start-demo.ps1          create instructor-demo/ (fails if it exists)
  .\start-demo.ps1 -Reset   delete any existing instructor-demo/ and recreate it
#>

param(
  [switch]$Reset
)

$ErrorActionPreference = "Stop"

$DemoDir = $PSScriptRoot
$SpeedrunDir = Join-Path $DemoDir "..\speedrun"
$Target = Join-Path $DemoDir "instructor-demo"

if ($Reset) {
  if (Test-Path $Target) {
    Write-Host "Removing existing $Target ..."
    Remove-Item -Recurse -Force $Target
  }
} elseif (Test-Path $Target) {
  Write-Error "'$Target' already exists. Re-run with -Reset to wipe and recreate it, or delete it yourself first if you're sure you don't need what's in it."
  exit 1
}

$SetupScript = Join-Path $SpeedrunDir "setup-team.ps1"
if (-not (Test-Path $SetupScript)) {
  Write-Error "Can't find $SetupScript -- is the speedrun\ folder next to demo\?"
  exit 1
}

Push-Location $DemoDir
try {
  & $SetupScript instructor-demo
} finally {
  Pop-Location
}

Write-Host ""
Write-Host "Demo repo ready at: $Target"
Write-Host "  warmup\                  -- empty, for live init/status/add/commit"
Write-Host "  cafe-project\             -- seeded repo, for everything else"
Write-Host "  cafe-project-origin.git\  -- the local fake remote"
Write-Host ""
Write-Host "Open demo-script.md and start teaching. Re-run this script with -Reset"
Write-Host "any time you want a clean slate (e.g. between class sessions)."
