#!/usr/bin/env bash
# Sets up (or resets) the instructor's own live-demo repo: the exact same
# Trailhead Cafe environment every team gets, generated by the already-tested
# speedrun/setup-team.sh under the hood. This is YOUR repo to drive at the
# front of the room while walking through demo-script.md and the visualizer
# -- separate from any team's folder, safe to reset between classes/runs.
#
# Usage:
#   ./start-demo.sh          create instructor-demo/ (fails if it exists)
#   ./start-demo.sh --reset  delete any existing instructor-demo/ and recreate it

set -euo pipefail

DEMO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SPEEDRUN_DIR="$DEMO_DIR/../speedrun"
TARGET="$DEMO_DIR/instructor-demo"

if [ "${1:-}" = "--reset" ]; then
  if [ -e "$TARGET" ]; then
    echo "Removing existing $TARGET ..."
    rm -rf "$TARGET"
  fi
elif [ -e "$TARGET" ]; then
  echo "Error: '$TARGET' already exists. Re-run with --reset to wipe and recreate it," >&2
  echo "or delete it yourself first if you're sure you don't need what's in it." >&2
  exit 1
fi

if [ ! -x "$SPEEDRUN_DIR/setup-team.sh" ] && [ ! -f "$SPEEDRUN_DIR/setup-team.sh" ]; then
  echo "Error: can't find $SPEEDRUN_DIR/setup-team.sh -- is the speedrun/ folder next to demo/?" >&2
  exit 1
fi

(cd "$DEMO_DIR" && bash "$SPEEDRUN_DIR/setup-team.sh" instructor-demo)

echo ""
echo "Demo repo ready at: $TARGET"
echo "  warmup/                  -- empty, for live init/status/add/commit"
echo "  cafe-project/             -- seeded repo, for everything else"
echo "  cafe-project-origin.git/  -- the local fake remote"
echo ""
echo "Open demo-script.md and start teaching. Re-run this script with --reset"
echo "any time you want a clean slate (e.g. between class sessions)."
